
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  trusted_proxies:
    - !env_var SECRET_TRUSTED_PROXIES_1
    - 172.31.30.0/24
  use_x_forwarded_for: True

zeroconf:
